version: "3"
services:
    www:
        build: .
        ports: 
            - "8001:80"
        volumes:
            - ./www:/var/www/html/
        links:
            - db
            - mailhog
        networks:
            - default
    db:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_DATABASE: 'myDb'
      # So you don't have to use root, but you can if you like
            MYSQL_USER: 'user'
      # You can use whatever password you like
            MYSQL_PASSWORD: 'password'
      # Password for root access
            MYSQL_ROOT_PASSWORD: 'password'
        ports:
      # <Port exposed> : < MySQL Port running inside container>
            - '3306:3306'
        expose:
      # Opens port 3306 on the container
            - '3306'
      # Where our data will be persisted
        volumes:
            - my-db:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db
        ports:
            - "8000:80"
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
    mailhog:
        image: phpdockerio/mailhog:latest
        container_name: mailhog
        ports:
            - "1025:1025"
            - "8002:8025"

volumes:
    my-db:
    persistent: